# Versão/Distribuição do Ubuntu.
os: linux
dist: focal

# Linguagem utilizada para desenvolver a aplicação.
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

# Instalação de módulos que são necessários para a aplicação.
install:
  - pip install flask pytest

# Criando etapa para o script de teste que deve rodar toda vez que o código for alterado.
script:
  - pytest -v test.py

# Definindo o deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-kleber
  on:
      branch: main